epicgame_channel = "your_channel_for_new_games"
hearstone_channel = "your_channel_for_update"
role_epicgame = "the role that you want to mension"
role_hearstone = "the role that you want to mension"
GUIL_ID = "Your guild ID"
epicgame_file = "cogs/epicgames_hearstone/jeux_gratuits.txt"
hearstone_file = "cogs/epicgames_hearstone/maj_hearstone.txt"
bot_token = "your discord token"